site_name: Investing Essentials
site_description: A primer for the novice investor plus tools, reference materials and educational resources for financial planning.
site_author: David Shore
site_url: https://investing-essentials.readthedocs.io
#site_url: http://0.0.0.0:8000/
theme:
  name: material
  favicon: assets/line_and_bar_chart.svg
  features:
    # - header.autohide # Keep off until hover over to reappear on desktop is an option.
    # - navigation.tracking
    # - navigation.expand # The navigation sidebar is too busy when always expanded.
    - navigation.footer
    - navigation.instant # The site_url setting must be set.
    - navigation.instant.prefetch # The site_url setting must be set (experimental feature)
    # - navigation.instant.preview # Currently an insiders (sponsors) only feature, but watch for free release.
    - navigation.path
    # - navigation.prune # Not needed for small sites.
    # - navigation.sections # Better than navigation expansion, but CSS needed to make navigation headers stand out.
    # - navigation.tabs # Moves top level section navigation to the header. Overrides sections.
    # - navigation.tabs.sticky # Keeps tabs on screen when scrolling.
    # - navigation.top # Shortcut to the top of the page appears when scrolling back up.
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow # Keeps active anchor in view in sidebar.
    # - toc.integrate # Makes navigation too busy. It is more manageable when tabs are enabled.
  font:
    text: Roboto
  logo: assets/investment_portfolio_vintage_2.1.svg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

#hooks: # The hook module will not be reloaded on each build running mkdocs serve.
 # - plugins\auto_copyright.py
plugins:
  - awesome-pages
  - glightbox
  - search

# Dev server binding
dev_addr: 0.0.0.0:8000